### ISSUE TITLE
Error with getting selected index in renderTabOption

### ISSUE THREAD

**Issue by egormerkushev** [kirankalyan5/react-native-segmented-control-tab#12]
Component doesn't update visual state if props changed via parent. Problem is in line 27 in method  `renderTabOption`: component gets selected index from self internal state, but it must get it from props. Also state is useless for this component in RN conception...
```
renderTabOption(tab, index) {
        const {values, borderRadius, selectedIndex} = this.props
        const isTabActive = selectedIndex === index
...
```

**Comment by egormerkushev** [comment]
Oh. Code above is from old version, but newer version has a same behaviour.

**Comment by kirankalyan5** [comment]
@egormerkushev - I have published the latest one, please have a look!

**Comment by SoundBlaster** [comment]
I had test with new version of code. Issue stays here.
Method `renderTabOption` uses `this.state` to get actual boolean active value for tab:
```
renderTabOption(tab, index) {
        const {values, borderRadius, multiple} = this.props
        const isTabActive = multiple ?
            this.state.selectedIndices.includes(index) :
            this.state.selectedIndex === index
```
but `this.state` becomes invalid if parent node rerenders self and included segmented control with new `prop` `selectedIndex` for it.

For example:
```
...
import SegmentedControlTab from 'react-native-segmented-control-tab'

class MyComplexComponent extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    return (
      <View style={[this.props.detailViewStyle.common, this.props.detailViewStyle.container, this.props.detailViewStyle.tabBarVisible]}>
        <SegmentedControlTab
          values={['Joined', 'Available']}
          selectedIndex={this.props.segmentedControlSelectedIndex}
          ....
        />
...
```
If value of `this.props.segmentedControlSelectedIndex` will be changed and `MyComplexComponent` will be rerendered for it (I use Redux in my React Native app - change may be caused by reducers and other stuff...) - then internal state 'this.state.selectedIndex' of segmented control will be corrupt.

**Comment by egormerkushev** [comment]
In my fork I removed `state` from component, but not test it with multiple=true
https://github.com/egormerkushev/react-native-segmented-control-tab/blob/master/SegmentedControlTab.js 

What do you think about necessity of `state` in your component? I think component like this must be clean aka "pure component".

**Comment by kirankalyan5** [comment]
@egormerkushev I feel you are referring to an older version!
The component is now a stateless functional component, Please refer [this](https://github.com/kirankalyan5/react-native-segmented-control-tab/blob/master/SegmentedControlTab.js)

**Comment by egormerkushev** [comment]
Yep, 3.0.1 works fine.
